apiVersion: v1
kind: Pod
metadata:
  name: employees-pod
  namespace: employees
  labels:
    app: employees
spec:
  imagePullSecrets:
  - name: ecr-pull-secret
  containers:
  - name: employees
    image: <ECR_WEB_URI>:v1
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: "mysql-svc-clusterip.mysql.svc.cluster.local"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    - name: DATABASE
      value: "employees"
    - name: APP_COLOR
      value: "blue"
