apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
      - name: ecr-pull-secret
      containers:
      - name: mysql
        image: <ECR_MYSQL_URI>:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
        - name: MYSQL_DATABASE
          value: "employees"
