name: Build and Push to ECR

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: us-east-1
  ACCOUNT_ID: "716057507063"
  WEBAPP_REPO: clo835-webapp
  MYSQL_REPO: clo835-mysql

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push WEBAPP
        run: |
          docker build --no-cache -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$WEBAPP_REPO:latest -f Dockerfile .
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$WEBAPP_REPO:latest

      - name: Build and push MYSQL
        run: |
          docker build --no-cache -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$MYSQL_REPO:latest -f Dockerfile_mysql .
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$MYSQL_REPO:latest

